config/routes.rb
Rottenpotatoes::Application.routes.draw do
  resources :movies
  # map '/' to be a redirect to '/movies'
  root to: redirect('/movies')
  get 'search' => 'movies#search_tmdb', as: 'search'
  post 'add_movie' => 'movies#add_movie', as: 'add_movie'
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  def self.all_ratings
    %w[G PG PG-13 R]
  end
  def self.find_in_tmdb(search_terms)
  end

  def self.with_ratings(ratings, sort_by)
    if ratings.nil?
      all.order sort_by
    else
      where(rating: ratings.map(&:upcase)).order sort_by
    end
  end
  def self.find_in_tmdb(search_params, api_key: '58087f4212acff8415de4471a8e44e19')
    # 这是TMDb API的基础URL
    base_url = "https://api.themoviedb.org/3/search/movie"
  
    # 构建查询参数哈希
    query_params = {
      api_key: api_key,
      query: search_params[:title],
      language: search_params[:language] || 'en-US' # 默认为 'en-US'
    }
    # 只有在 release_year 存在时才添加它
    query_params[:year] = search_params[:release_year] if search_params[:release_year].present?
  
    begin
      # Faraday.get 会自动把 query_params 转换成 URL
      # 这个调用会被 spec/spec_helper.rb 里的 WebMock 存根(stub)拦截
      response = Faraday.get(base_url, query_params)
  
      if response.success?
        # 解析 JSON 字符串
        json_results = JSON.parse(response.body)
  
        # "return a list of movies that have NOT been saved"
        # 我们把 JSON 结果数组 转换成 Movie 对象数组
        movies = json_results['results'].map do |movie_data|
          Movie.new(
            title: movie_data['title'],
            release_date: movie_data['release_date'],
            rating: 'R', # "you should just put 'R' for all of them"
            description: movie_data['overview']
          )
        end
        return movies
      else
        return [] # API 报告错误 (例如，错误的 API 密钥)
      end
    rescue Faraday::Error, JSON::ParserError
      return [] # 发生连接错误或 JSON 解析错误
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # 这些是TDD作业开始时就应该存在的标准方法
  def index
    # --- 这是修复补丁 ---
    # 你的视图 (view) 需要这些来自旧作业的变量
    @all_ratings = Movie.all_ratings
    @ratings_to_show_hash = {}
    @sort_by = nil
    # --- 补丁结束 ---
  
    @movies = Movie.all
  end

  def show
    id = params[:id]
    @movie = Movie.find(id)
  end

  def new
    # 默认: 渲染 'new' 模板
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  # --- 这是我们正在TDD的方法 ---
  def search_tmdb
    search_params = params["search"] || {} # 使用字符串键

    if search_params["title"].blank? # 使用字符串键
      flash.now[:warning] = "Please fill in all required fields!"
      @movies = []
    else
      @movies = Movie.find_in_tmdb(search_params)
      if @movies.empty?
        flash.now[:warning] = "No movies found with given parameters!"
      end
    end
  end


  # --- 把这个新方法粘贴在这里 ---
  def add_movie
    # 1. 使用 strong parameters (movie_params) 来安全地创建电影
    #    '.save' 会返回 true/false
    @movie = Movie.new(movie_params)

    if @movie.save
      # 2. 设置 flash 消息 (匹配我们的测试)
      flash[:success] = "'#{@movie.title}' was successfully added to RottenPotatoes."

      # 3. 重定向到主页 (匹配我们的测试)
      redirect_to movies_path
    else
      # 如果保存失败 (例如，如果未来添加了验证)
      flash[:warning] = "Failed to add movie."
      redirect_to search_tmdb_path # 重定向回搜索页
    end
  end

private
# ...

  private
  # 确保 movie_params 存在
  def movie_params
    params.require(:movie).permit(:title, :rating, :description, :release_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ? "odd" : "even"
  end
end

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<%# Our "base" layout should be a valid HTML document. %>
<!DOCTYPE html>
<html>
  <head>
    <title>Rotten Potatoes!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', 'media' => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# These classes come from the Bootstrap CSS framework. %>
    <nav class="navbar navbar-expand-lg bg-primary text-white mb-3">
      <h1 class="title">Rotten Potatoes!</h1>
    </nav>
    <div class="container">
      <%# Render "flash" messages in our application. This loads _flash.erb %>
      <%= render 'layouts/flash' %>
      <main id="main">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/movies/edit.html.erb
<h2>Edit Existing Movie</h2>
<%= form_tag movie_path(@movie), :method => :put do %>
  <%= label :movie, :title, 'Title', class: 'col-form-label' %>
  <%= text_field :movie, 'title', class: 'form-control' %>
  <%= label :movie, :rating, 'Rating', class: 'col-form-label'  %>
  <%= select :movie, :rating, ['G','PG','PG-13','R'], {}, {class: 'form-control col-1'} %>
  <%= label :movie, :release_date, 'Released On', class: 'col-form-label'  %>
  <%= date_select :movie, :release_date, {}, class: 'form-control col-2 d-inline' %>
  <br/>
  <%= submit_tag 'Update Movie Info', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', movies_path, class: 'btn btn-secondary' %>
<% end %>

app/views/movies/index.html.erb
<!--  This file is app/views/movies/index.html.erb -->
<h2>All Movies</h2>

<div class="row navigation">
  <div class="col-md-10">
    <%= form_tag movies_path, method: :get, id: 'ratings_form' do %>
      <%= hidden_field_tag 'sort_by', @sort_by %>
      Include:
      <% @all_ratings.each do |rating| %>
        <div class="form-check  form-check-inline">
          <%= label_tag "ratings[#{rating}]", rating, class: 'form-check-label' %>
          <%= check_box_tag "ratings[#{rating}]", '1', (@ratings_to_show_hash.include?(rating)),
            class: 'form-check-input' %>
        </div>
      <% end %>
      <%= submit_tag 'Refresh', id: 'ratings_submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class="col-md-2">
    <%# Part 1 here %>
  </div>

</div>

<table class="table table-striped col-md-12" id="movies">
  <thead>
    <tr>
      <th>
        <%= link_to 'Movie Title', movies_path({sort_by: 'title', ratings: @ratings_to_show_hash}),
                      id: 'title_header', class: ('bg-warning hilite' if @sort_by == 'title') %>
      </th>
      <th>Rating</th>
      <th>
        <%= link_to 'Release Date',
              movies_path({sort_by: 'release_date', ratings: @ratings_to_show_hash}),
              id: 'release_date_header', class: ('bg-warning hilite' if @sort_by == 'release_date') %>
      </th>
      <th>More Info</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>
          <%= movie.title %>
        </td>
        <td>
          <%= movie.rating %>
        </td>
        <td>
          <%= movie.release_date %>
        </td>
        <td>
          <%= link_to "More about #{movie.title}", movie_path(movie) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add new movie', new_movie_path, class: 'btn btn-primary' %>
<%= link_to "New movie", new_movie_path %>
<%= link_to "Search TMDb", search_path %>

app/views/movies/new.html.erb
<h2>Create New Movie</h2>

<%= form_tag movies_path, class: 'form' do %>
  <%= label :movie, :title, 'Title', class: 'col-form-label' %>
  <%= text_field :movie, :title, class: 'form-control' %>
  <%= label :movie, :rating, 'Rating', class: 'col-form-label' %>
  <%= select :movie, :rating, ['G','PG','PG-13','R'], {}, {class: 'form-control col-1'} %>
  <%= label :movie, :release_date, 'Released On', class: 'col-form-label' %>
  <%= date_select :movie, :release_date, {}, class: 'form-control col-2 d-inline' %>
  <br/>
  <%= submit_tag 'Save Changes', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', movies_path, class: 'btn btn-secondary' %>
<% end %>

app/views/movies/search_tmdb.html.erb
<%# 这是指南要求的 flash 消息显示 %>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <%= value %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<h1>Search TMDb</h1>

<%= form_tag search_path, method: :get, id: 'tmdb_form' do %>

  <%# 
    这些字段将生成一个哈希: params[:search]
    例如: params[:search][:title] 
  %>
  <div>
    <%= label_tag 'search[title]', 'Title' %>
    <%= text_field_tag 'search[title]', params.dig(:search, :title), id: 'movie_title_field' %>
  </div>
  <div>
    <%= label_tag 'search[release_year]', 'Release Year (Optional)' %>
    <%= text_field_tag 'search[release_year]', params.dig(:search, :release_year), id: 'movie_year_field' %>
  </div>
  <div>
    <%= label_tag 'search[language]', 'Language' %>
    <%= text_field_tag 'search[language]', params.dig(:search, :language) || 'en-US' %>
  </div>

  <%= submit_tag 'Search', id: 'tmdb_submit' %>
<% end %>

<br/>
<%# 这是指南要求的“添加结果表格” %>
<% if @movies.present? %>
  <table class="table" id="search_movies">
    <thead>
      <tr>
        <th>Title</th>
        <th>Release Date</th>
        <th>Description</th>
        <th>Add to RottenPotatoes</th>
      </tr>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= movie.title %></td>
          <td><%= movie.release_date %></td>
          <td><%= movie.description %></td>
          <td>
            <%#
              这是“Add movie”按钮。它是一个自己的小表单，
              会将数据 POST 到 'add_movie_path' (我们下一步创建它)。
            %>
            <%= form_tag add_movie_path, method: :post do %>
              <%# 使用 hidden_field_tag 来“秘密”传递数据 %>
              <%= hidden_field_tag 'movie[title]', movie.title %>
              <%= hidden_field_tag 'movie[release_date]', movie.release_date %>
              <%= hidden_field_tag 'movie[rating]', movie.rating %>
              <%= hidden_field_tag 'movie[description]', movie.description %>
              <%= submit_tag 'Add movie' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%# 这是你之前添加的 "Back" 链接 %>
<%= link_to 'Back to list', movies_path %>

app/views/movies/show.html.erb
<!--  app/views/movies/show.html.erb -->
<h2>Details about <em><%= @movie.title %></em></h2>

<ul id="details">
  <li>
    Rating:
    <%= @movie.rating %>
  </li>
  <li>
    Released on:
    <%= @movie.release_date.strftime("%B %d, %Y") %>
  </li>
</ul>

<h3>Description:</h3>
<p id="description">
  <%= @movie.description %>
</p>

<div class="row">
  <%= link_to 'Edit', edit_movie_path(@movie), class: 'btn btn-primary col-2' %>
  <%= link_to 'Delete', movie_path(@movie), 'data-method': 'delete', 'data-confirm': 'Are you sure?', class: 'btn btn-danger col-2' %>
  <%= link_to 'Back to movie list', movies_path, class: 'btn btn-primary col-2' %>
</div>